/* Generated By:JJTree: Do not edit this line. ASTAdditiveMinusNode.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTAdditiveMinusNode extends SimpleNode {
  public ASTAdditiveMinusNode(int id) {
    super(id);
  }

  public ASTAdditiveMinusNode(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTAdditiveMinusNode(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTAdditiveMinusNode(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
