/* Generated By:JJTree: Do not edit this line. ASTAssignNode.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTAssignNode extends SimpleNode {
  public ASTAssignNode(int id) {
    super(id);
  }

  public ASTAssignNode(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTAssignNode(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTAssignNode(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
