/* Generated By:JJTree: Do not edit this line. ASTApplicationExpression.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTApplicationExpression extends SimpleNode {
  public ASTApplicationExpression(int id) {
    super(id);
  }

  public ASTApplicationExpression(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTApplicationExpression(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTApplicationExpression(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
