/* Generated By:JJTree: Do not edit this line. ASTAdditivePlusNode.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTAdditivePlusNode extends SimpleNode {
  public ASTAdditivePlusNode(int id) {
    super(id);
  }

  public ASTAdditivePlusNode(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTAdditivePlusNode(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTAdditivePlusNode(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
