/* Generated By:JJTree: Do not edit this line. ASTCommonLeftBracketExpression.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTCommonLeftBracketExpression extends SimpleNode {
	public ASTCommonLeftBracketExpression(int id) {
		super(id);
	}

	public ASTCommonLeftBracketExpression(SimPLParser p, int id) {
		super(p, id);
	}

	public static Node jjtCreate(int id) {
		return new ASTCommonLeftBracketExpression(id);
	}

	public static Node jjtCreate(SimPLParser p, int id) {
		return new ASTCommonLeftBracketExpression(p, id);
	}

	/**
	 * Accept the visitor.
	 * 
	 * @throws TypeException
	 * @throws InterpretException
	 **/
	public Object jjtAccept(SimPLParserVisitor visitor, Object data)
			throws TypeException, InterpretException {
		return visitor.visit(this, data);
	}

	public String toString() {
		return "(" + this.jjtGetChild(0).toString() + " "
				+ this.jjtGetChild(1).toString();
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof ASTCommonLeftBracketExpression)) {
			return false;
		}

		ASTCommonLeftBracketExpression otherNode = (ASTCommonLeftBracketExpression) obj;

		return this.jjtGetChild(0).equals(otherNode.jjtGetChild(0))
				&& this.jjtGetChild(1).equals(otherNode.jjtGetChild(1));
	}

}
