/* Generated By:JJTree: Do not edit this line. ASTCommonLeftBracketExpression.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTCommonLeftBracketExpression extends SimpleNode {
  public ASTCommonLeftBracketExpression(int id) {
    super(id);
  }

  public ASTCommonLeftBracketExpression(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTCommonLeftBracketExpression(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTCommonLeftBracketExpression(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
