/* Generated By:JJTree: Do not edit this line. ASTEqualityEqualNode.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTEqualityEqualNode extends SimpleNode {
  public ASTEqualityEqualNode(int id) {
    super(id);
  }

  public ASTEqualityEqualNode(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTEqualityEqualNode(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTEqualityEqualNode(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
