/* Generated By:JJTree: Do not edit this line. ASTExpression.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTExpression extends SimpleNode {
	public ASTExpression(int id) {
		super(id);
	}

	public ASTExpression(SimPLParser p, int id) {
		super(p, id);
	}

	public static Node jjtCreate(int id) {
		return new ASTExpression(id);
	}

	public static Node jjtCreate(SimPLParser p, int id) {
		return new ASTExpression(p, id);
	}

	/**
	 * Accept the visitor.
	 * 
	 * @throws TypeException
	 * @throws InterpretException
	 **/
	public Object jjtAccept(SimPLParserVisitor visitor, Object data)
			throws TypeException, InterpretException {
		return visitor.visit(this, data);
	}

	public String toString() {
		return this.jjtGetChild(0).toString();
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof ASTExpression)) {
			return false;
		}
		ASTExpression otherNode = (ASTExpression) obj;

		return this.jjtGetChild(0).equals(otherNode.jjtGetChild(0));
	}
}
