/* Generated By:JJTree: Do not edit this line. ASTEqualityBiggerThanNode.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTEqualityBiggerThanNode extends SimpleNode {
  public ASTEqualityBiggerThanNode(int id) {
    super(id);
  }

  public ASTEqualityBiggerThanNode(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTEqualityBiggerThanNode(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTEqualityBiggerThanNode(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
