/* Generated By:JJTree: Do not edit this line. ASTEqualityLessThanNode.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTEqualityLessThanNode extends SimpleNode {
	public ASTEqualityLessThanNode(int id) {
		super(id);
	}

	public ASTEqualityLessThanNode(SimPLParser p, int id) {
		super(p, id);
	}

	public static Node jjtCreate(int id) {
		return new ASTEqualityLessThanNode(id);
	}

	public static Node jjtCreate(SimPLParser p, int id) {
		return new ASTEqualityLessThanNode(p, id);
	}

	/**
	 * Accept the visitor.
	 * 
	 * @throws TypeException
	 * @throws InterpretException
	 **/
	public Object jjtAccept(SimPLParserVisitor visitor, Object data)
			throws TypeException, InterpretException {
		return visitor.visit(this, data);
	}

	public String toString() {
		return this.jjtGetChild(0).toString() + " < "
				+ this.jjtGetChild(1).toString();
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof ASTEqualityLessThanNode)) {
			return false;
		}

		ASTEqualityLessThanNode otherNode = (ASTEqualityLessThanNode) obj;

		return this.jjtGetChild(0).equals(otherNode.jjtGetChild(0))
				&& this.jjtGetChild(1).equals(otherNode.jjtGetChild(1));
	}
}
