/* Generated By:JJTree: Do not edit this line. ASTFirstOfPairExpression.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTFirstOfPairExpression extends SimpleNode {
  public ASTFirstOfPairExpression(int id) {
    super(id);
  }

  public ASTFirstOfPairExpression(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTFirstOfPairExpression(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTFirstOfPairExpression(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
