/* Generated By:JJTree: Do not edit this line. ASTIfThenElseExpression.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTIfThenElseExpression extends SimpleNode {
  public ASTIfThenElseExpression(int id) {
    super(id);
  }

  public ASTIfThenElseExpression(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTIfThenElseExpression(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTIfThenElseExpression(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
