/* Generated By:JJTree: Do not edit this line. ASTJoinNode.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTJoinNode extends SimpleNode {
	public ASTJoinNode(int id) {
		super(id);
	}

	public ASTJoinNode(SimPLParser p, int id) {
		super(p, id);
	}

	public static Node jjtCreate(int id) {
		return new ASTJoinNode(id);
	}

	public static Node jjtCreate(SimPLParser p, int id) {
		return new ASTJoinNode(p, id);
	}

	/**
	 * Accept the visitor.
	 * 
	 * @throws TypeException
	 * @throws InterpretException
	 **/
	public Object jjtAccept(SimPLParserVisitor visitor, Object data)
			throws TypeException, InterpretException {
		return visitor.visit(this, data);
	}

	public String toString() {
		return this.jjtGetChild(0).toString() + " :: "
				+ this.jjtGetChild(1).toString();
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof ASTJoinNode)) {
			return false;
		}

		ASTJoinNode otherNode = (ASTJoinNode) obj;

		return this.jjtGetChild(0).equals(otherNode.jjtGetChild(0))
				&& this.jjtGetChild(1).equals(otherNode.jjtGetChild(1));
	}

}
