/* Generated By:JJTree: Do not edit this line. ASTLetExpression.java */

package javacc;

import java.util.HashMap;

import utils.InterpretException;
import utils.TypeException;

public class ASTLetExpression extends SimpleNode {

	HashMap<String, SimpleNode> parentEnv;

	public HashMap<String, SimpleNode> getParentEnv() {
		return parentEnv;
	}

	public void setParentEnv(HashMap<String, SimpleNode> parentEnv) {
		this.parentEnv = parentEnv;
	}

	public ASTLetExpression(int id) {
		super(id);
	}

	public ASTLetExpression(SimPLParser p, int id) {
		super(p, id);
	}

	public static Node jjtCreate(int id) {
		return new ASTLetExpression(id);
	}

	public static Node jjtCreate(SimPLParser p, int id) {
		return new ASTLetExpression(p, id);
	}

	/**
	 * Accept the visitor.
	 * 
	 * @throws TypeException
	 * @throws InterpretException
	 **/
	public Object jjtAccept(SimPLParserVisitor visitor, Object data)
			throws TypeException, InterpretException {
		return visitor.visit(this, data);
	}
}
