/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeMultiplyNode.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTMultiplicativeMultiplyNode extends SimpleNode {
  public ASTMultiplicativeMultiplyNode(int id) {
    super(id);
  }

  public ASTMultiplicativeMultiplyNode(SimPLParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTMultiplicativeMultiplyNode(id);
  }

  public static Node jjtCreate(SimPLParser p, int id) {
      return new ASTMultiplicativeMultiplyNode(p, id);
  }

  /** Accept the visitor. 
 * @throws TypeException 
 * @throws InterpretException **/
  public Object jjtAccept(SimPLParserVisitor visitor, Object data) throws TypeException, InterpretException {
    return visitor.visit(this, data);
  }
}
