/* Generated By:JJTree: Do not edit this line. ASTVariable.java */

package javacc;

import utils.InterpretException;
import utils.TypeException;

public class ASTVariable extends SimpleNode {

	private String name;

	public ASTVariable(int id) {
		super(id);
	}

	public ASTVariable(SimPLParser p, int id) {
		super(p, id);
	}

	public static Node jjtCreate(int id) {
		return new ASTVariable(id);
	}

	public static Node jjtCreate(SimPLParser p, int id) {
		return new ASTVariable(p, id);
	}

	/**
	 * Accept the visitor.
	 * 
	 * @throws TypeException
	 * @throws InterpretException
	 **/
	public Object jjtAccept(SimPLParserVisitor visitor, Object data)
			throws TypeException, InterpretException {
		return visitor.visit(this, data);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String toString() {
		return this.name;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof ASTVariable)) {
			return false;
		}

		ASTVariable otherNode = (ASTVariable) obj;

		return this.name.equals(otherNode.name);
	}

}
