/* Generated By:JJTree&JavaCC: Do not edit this line. SimPLParserConstants.java */
package javacc;

public interface SimPLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int PLUS = 10;
  int MINUS = 11;
  int MULTIPLY = 12;
  int DIVIDE = 13;
  int NEGATIVE = 14;
  int EQUAL = 15;
  int LESSTHAN = 16;
  int BIGGERTHAN = 17;
  int ARROW = 18;
  int JOIN = 19;
  int ASSIGN = 20;
  int SEMICOLON = 21;
  int LPAREN = 22;
  int RPAREN = 23;
  int COMMA = 24;
  int LET = 25;
  int IN = 26;
  int END = 27;
  int IF = 28;
  int THEN = 29;
  int ELSE = 30;
  int WHILE = 31;
  int DO = 32;
  int FIRST = 33;
  int SECOND = 34;
  int HEAD = 35;
  int TAIL = 36;
  int NIL = 37;
  int INT = 38;
  int BOOL = 39;
  int AND = 40;
  int OR = 41;
  int NOT = 42;
  int FUN = 43;
  int TRUE = 44;
  int FALSE = 45;
  int LIST = 46;
  int UNIT = 47;
  int INTEGER = 48;
  int DIGIT = 49;
  int IDENTIFIER = 50;
  int LETTER = 51;
  int NOP = 52;

  int DEFAULT = 0;
  int INSIDE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"->\"",
    "\"::\"",
    "\":=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"fst\"",
    "\"snd\"",
    "\"head\"",
    "\"tail\"",
    "\"nil\"",
    "\"int\"",
    "\"bool\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"fun\"",
    "\"true\"",
    "\"false\"",
    "\"list\"",
    "\"unit\"",
    "<INTEGER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<NOP>",
  };

}
