/* Generated By:JJTree&JavaCC: Do not edit this line. SimPLParserConstants.java */
package javacc;

public interface SimPLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 1;
  int MULTI_LINE_COMMENT = 2;
  int PLUS = 7;
  int MINUS = 8;
  int MULTIPLY = 9;
  int DIVIDE = 10;
  int NEGATIVE = 11;
  int EQUAL = 12;
  int LESSTHAN = 13;
  int BIGGERTHAN = 14;
  int ARROW = 15;
  int JOIN = 16;
  int ASSIGN = 17;
  int SEMICOLON = 18;
  int LPAREN = 19;
  int RPAREN = 20;
  int COMMA = 21;
  int LET = 22;
  int IN = 23;
  int END = 24;
  int IF = 25;
  int THEN = 26;
  int ELSE = 27;
  int WHILE = 28;
  int DO = 29;
  int FIRST = 30;
  int SECOND = 31;
  int HEAD = 32;
  int TAIL = 33;
  int NIL = 34;
  int INT = 35;
  int BOOL = 36;
  int AND = 37;
  int OR = 38;
  int NOT = 39;
  int FUN = 40;
  int TRUE = 41;
  int FALSE = 42;
  int LIST = 43;
  int UNIT = 44;
  int INTEGER = 45;
  int DIGIT = 46;
  int IDENTIFIER = 47;
  int LETTER = 48;
  int NOP = 49;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"->\"",
    "\"::\"",
    "\":=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"fst\"",
    "\"snd\"",
    "\"head\"",
    "\"tail\"",
    "\"nil\"",
    "\"int\"",
    "\"bool\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"fun\"",
    "\"true\"",
    "\"false\"",
    "\"list\"",
    "\"unit\"",
    "<INTEGER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<NOP>",
  };

}
